### ISSUE TITLE
Discord not found

### ISSUE THREAD

**Issue by BlidaBall** [RealistikDash/PyCord#1]
when i run it it says discord not found or smth help

**Comment by RealistikDash** [comment]
If you're running Windows, please make sure you have python 3.6.5 or newer installed and added it to path. Now run cmd with administrator privileges and run the following command:

`pip install discord.py`

If the problem proceeds, redownload the script and make sure you only edit the token line and no other code.

If none of those fixed, please proceed to make another issue.

**Comment by BlidaBall** [comment]
okthxworks
